<?php

namespace App\Http\Controllers\Dev;

use App\Http\Controllers\Controller;
use Illuminate\View\View;

/**
 * Temporary, dev-only: renders the same customer card UI in a few candidate
 * visual themes so a theme can be picked by eye before it's baked into the
 * real Stage 0 layout. Deleted once a theme is chosen.
 */
class ThemePreviewController extends Controller
{
    /**
     * @return array<string, array<string, mixed>>
     */
    public static function themes(): array
    {
        return [
            'warm-artisan' => [
                'name' => 'Warm Artisan',
                'blurb' => 'Cafe & bakery feel — terracotta and cream, soft rounded cards.',
                'google_fonts' => 'Playfair+Display:wght@600;700|Nunito+Sans:wght@400;600;700',
                'heading_font' => "'Playfair Display', serif",
                'body_font' => "'Nunito Sans', sans-serif",
                'page_bg' => '#FBF3E7',
                'card_bg' => '#FFFDF9',
                'text' => '#3E2723',
                'muted' => '#8D7B68',
                'accent' => '#C1653B',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#C1653B',
                'stamp_empty' => '#EFE0CE',
                'border' => '#EFE0CE',
                'radius' => '24px',
                'button_radius' => '9999px',
                'shadow' => '0 8px 24px -8px rgba(62,39,35,0.25)',
            ],
            'modern-minimal' => [
                'name' => 'Modern Minimal',
                'blurb' => 'Neutral and crisp — works for any shop type, low visual noise.',
                'google_fonts' => 'Inter:wght@400;500;600;700',
                'heading_font' => "'Inter', sans-serif",
                'body_font' => "'Inter', sans-serif",
                'page_bg' => '#FAFAF9',
                'card_bg' => '#FFFFFF',
                'text' => '#1C1917',
                'muted' => '#78716C',
                'accent' => '#10B981',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#10B981',
                'stamp_empty' => '#E7E5E4',
                'border' => '#E7E5E4',
                'radius' => '10px',
                'button_radius' => '8px',
                'shadow' => '0 1px 3px 0 rgba(0,0,0,0.08)',
            ],
            'bold-local' => [
                'name' => 'Bold Local',
                'blurb' => 'High-contrast navy and amber — pops on a phone screen at arm\'s length.',
                'google_fonts' => 'Poppins:wght@500;600;700;800',
                'heading_font' => "'Poppins', sans-serif",
                'body_font' => "'Poppins', sans-serif",
                'page_bg' => '#0B1F3A',
                'card_bg' => '#122A4D',
                'text' => '#FFFFFF',
                'muted' => '#9FB3D1',
                'accent' => '#F5A623',
                'accent_text' => '#1B1200',
                'stamp_filled' => '#F5A623',
                'stamp_empty' => '#1E3A63',
                'border' => '#1E3A63',
                'radius' => '28px',
                'button_radius' => '9999px',
                'shadow' => '0 8px 24px -8px rgba(0,0,0,0.5)',
            ],
            'classic-british' => [
                'name' => 'Classic British',
                'blurb' => 'Pub & barber heritage — deep green with brass accents, traditional serif.',
                'google_fonts' => 'Libre+Baskerville:wght@400;700|Inter:wght@400;500;600',
                'heading_font' => "'Libre Baskerville', serif",
                'body_font' => "'Inter', sans-serif",
                'page_bg' => '#12261E',
                'card_bg' => '#173328',
                'text' => '#F3EFE6',
                'muted' => '#A9BDB1',
                'accent' => '#C9A227',
                'accent_text' => '#1B1502',
                'stamp_filled' => '#C9A227',
                'stamp_empty' => '#2A4A3B',
                'border' => '#2A4A3B',
                'radius' => '18px',
                'button_radius' => '6px',
                'shadow' => '0 8px 24px -8px rgba(0,0,0,0.45)',
            ],
            'pastel-bakery' => [
                'name' => 'Pastel Bakery',
                'blurb' => 'Sweets & bakery feel — bubblegum pink, playful rounded shapes.',
                'google_fonts' => 'Fredoka:wght@600;700|Quicksand:wght@400;500;600',
                'heading_font' => "'Fredoka', sans-serif",
                'body_font' => "'Quicksand', sans-serif",
                'page_bg' => '#FDF0F5',
                'card_bg' => '#FFFFFF',
                'text' => '#4A2E3B',
                'muted' => '#B98CA0',
                'accent' => '#F582AE',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#F582AE',
                'stamp_empty' => '#F6DCE6',
                'border' => '#F6DCE6',
                'radius' => '28px',
                'button_radius' => '9999px',
                'shadow' => '0 8px 20px -8px rgba(245,130,174,0.35)',
            ],
            'monochrome-barber' => [
                'name' => 'Monochrome Barber',
                'blurb' => 'Black, white and barber-pole red — sharp corners, condensed type.',
                'google_fonts' => 'Oswald:wght@500;600;700|Inter:wght@400;500',
                'heading_font' => "'Oswald', sans-serif",
                'body_font' => "'Inter', sans-serif",
                'page_bg' => '#F5F5F5',
                'card_bg' => '#FFFFFF',
                'text' => '#111111',
                'muted' => '#6B6B6B',
                'accent' => '#C1272D',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#111111',
                'stamp_empty' => '#E0E0E0',
                'border' => '#E0E0E0',
                'radius' => '4px',
                'button_radius' => '4px',
                'shadow' => '0 1px 2px 0 rgba(0,0,0,0.1)',
            ],
            'sunset-coffee' => [
                'name' => 'Sunset Coffee',
                'blurb' => 'Peach and coral warmth — a softer, friendlier take on cafe branding.',
                'google_fonts' => 'Fraunces:wght@600;700|Nunito+Sans:wght@400;600',
                'heading_font' => "'Fraunces', serif",
                'body_font' => "'Nunito Sans', sans-serif",
                'page_bg' => '#FFE8D6',
                'card_bg' => '#FFF8F0',
                'text' => '#5C2E1E',
                'muted' => '#B08968',
                'accent' => '#FF6F59',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#FF6F59',
                'stamp_empty' => '#FFD8C2',
                'border' => '#FFD8C2',
                'radius' => '20px',
                'button_radius' => '9999px',
                'shadow' => '0 8px 20px -8px rgba(255,111,89,0.3)',
            ],
            'industrial-loft' => [
                'name' => 'Industrial Loft',
                'blurb' => 'Concrete grey and safety orange — exposed-brick roastery feel.',
                'google_fonts' => 'Archivo+Black|Inter:wght@400;500',
                'heading_font' => "'Archivo Black', sans-serif",
                'body_font' => "'Inter', sans-serif",
                'page_bg' => '#2B2B2B',
                'card_bg' => '#3A3A3A',
                'text' => '#F2F2F2',
                'muted' => '#A0A0A0',
                'accent' => '#FF7A00',
                'accent_text' => '#1A1200',
                'stamp_filled' => '#FF7A00',
                'stamp_empty' => '#4A4A4A',
                'border' => '#4A4A4A',
                'radius' => '6px',
                'button_radius' => '6px',
                'shadow' => '0 8px 20px -8px rgba(0,0,0,0.5)',
            ],
            'botanical-green' => [
                'name' => 'Botanical Green',
                'blurb' => 'Sage and cream with a delicate serif — plant-shop, artisan calm.',
                'google_fonts' => 'Cormorant+Garamond:wght@600;700|Karla:wght@400;500;600',
                'heading_font' => "'Cormorant Garamond', serif",
                'body_font' => "'Karla', sans-serif",
                'page_bg' => '#F4F6F1',
                'card_bg' => '#FFFFFF',
                'text' => '#2F3E2E',
                'muted' => '#7C8D74',
                'accent' => '#5C7A52',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#5C7A52',
                'stamp_empty' => '#E1E8DC',
                'border' => '#E1E8DC',
                'radius' => '16px',
                'button_radius' => '9999px',
                'shadow' => '0 4px 16px -6px rgba(47,62,46,0.2)',
            ],
            'neon-nightlife' => [
                'name' => 'Neon Nightlife',
                'blurb' => 'Deep purple-black with neon pink and cyan — late-night bar energy.',
                'google_fonts' => 'Space+Grotesk:wght@500;600;700',
                'heading_font' => "'Space Grotesk', sans-serif",
                'body_font' => "'Space Grotesk', sans-serif",
                'page_bg' => '#14071F',
                'card_bg' => '#1F0E30',
                'text' => '#F4EAFF',
                'muted' => '#B79FD4',
                'accent' => '#FF2E93',
                'accent_text' => '#0D0014',
                'stamp_filled' => '#29F1C3',
                'stamp_empty' => '#2E1A42',
                'border' => '#2E1A42',
                'radius' => '18px',
                'button_radius' => '9999px',
                'shadow' => '0 0 24px -4px rgba(255,46,147,0.45)',
            ],
            'seaside-pastel' => [
                'name' => 'Seaside Pastel',
                'blurb' => 'Pale aqua and sand — light, airy, coastal cafe feel.',
                'google_fonts' => 'Comfortaa:wght@600;700|Mulish:wght@400;500;600',
                'heading_font' => "'Comfortaa', sans-serif",
                'body_font' => "'Mulish', sans-serif",
                'page_bg' => '#EAF6F6',
                'card_bg' => '#FFFFFF',
                'text' => '#234E52',
                'muted' => '#7FA8AC',
                'accent' => '#4FB5BE',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#4FB5BE',
                'stamp_empty' => '#D6ECEC',
                'border' => '#D6ECEC',
                'radius' => '20px',
                'button_radius' => '9999px',
                'shadow' => '0 8px 20px -8px rgba(79,181,190,0.3)',
            ],
            'vintage-barbershop' => [
                'name' => 'Vintage Barbershop',
                'blurb' => 'Cream and deep barber red — bold vintage display type.',
                'google_fonts' => 'Abril+Fatface|Lora:wght@400;500;600',
                'heading_font' => "'Abril Fatface', serif",
                'body_font' => "'Lora', serif",
                'page_bg' => '#F2E8D5',
                'card_bg' => '#FFFDF6',
                'text' => '#3B1F1F',
                'muted' => '#8A6A5C',
                'accent' => '#7A1F2B',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#7A1F2B',
                'stamp_empty' => '#E6D3B3',
                'border' => '#E6D3B3',
                'radius' => '8px',
                'button_radius' => '6px',
                'shadow' => '0 6px 16px -6px rgba(59,31,31,0.3)',
            ],
            'scandinavian-minimal' => [
                'name' => 'Scandinavian Minimal',
                'blurb' => 'Warm white and wood-tone beige — very clean, Nordic cafe aesthetic.',
                'google_fonts' => 'Work+Sans:wght@400;500;600;700',
                'heading_font' => "'Work Sans', sans-serif",
                'body_font' => "'Work Sans', sans-serif",
                'page_bg' => '#FAF8F5',
                'card_bg' => '#FFFFFF',
                'text' => '#2B2B2B',
                'muted' => '#8C8C8C',
                'accent' => '#B08968',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#B08968',
                'stamp_empty' => '#EDE7DE',
                'border' => '#EDE7DE',
                'radius' => '4px',
                'button_radius' => '4px',
                'shadow' => '0 1px 3px 0 rgba(0,0,0,0.06)',
            ],
            'craft-ale-pub' => [
                'name' => 'Craft Ale Pub',
                'blurb' => 'Deep brown and amber ale — sturdy slab serif, traditional brewery feel.',
                'google_fonts' => 'Bitter:wght@600;700|Inter:wght@400;500',
                'heading_font' => "'Bitter', serif",
                'body_font' => "'Inter', sans-serif",
                'page_bg' => '#2B1B12',
                'card_bg' => '#3A2618',
                'text' => '#F4E9D8',
                'muted' => '#C4A788',
                'accent' => '#E8A33D',
                'accent_text' => '#241100',
                'stamp_filled' => '#E8A33D',
                'stamp_empty' => '#4A3421',
                'border' => '#4A3421',
                'radius' => '10px',
                'button_radius' => '8px',
                'shadow' => '0 8px 20px -8px rgba(0,0,0,0.5)',
            ],
            'retro-diner' => [
                'name' => 'Retro Diner',
                'blurb' => 'Cream and cherry red — bold retro-signage type, chunky rounded cards.',
                'google_fonts' => 'Bungee|Inter:wght@400;500',
                'heading_font' => "'Bungee', sans-serif",
                'body_font' => "'Inter', sans-serif",
                'page_bg' => '#FFF7EC',
                'card_bg' => '#FFFFFF',
                'text' => '#2B2320',
                'muted' => '#8A7A6B',
                'accent' => '#D62839',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#D62839',
                'stamp_empty' => '#F5DCC8',
                'border' => '#F0DCC8',
                'radius' => '16px',
                'button_radius' => '9999px',
                'shadow' => '0 8px 20px -8px rgba(214,40,57,0.3)',
            ],
            'tea-room-garden' => [
                'name' => 'Tea Room Garden',
                'blurb' => 'Blush white and dusty rose — delicate serif, English tea-room feel.',
                'google_fonts' => 'EB+Garamond:wght@500;600|Nunito:wght@400;600',
                'heading_font' => "'EB Garamond', serif",
                'body_font' => "'Nunito', sans-serif",
                'page_bg' => '#FBF1F0',
                'card_bg' => '#FFFFFF',
                'text' => '#4A3B3E',
                'muted' => '#B292A0',
                'accent' => '#C08497',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#C08497',
                'stamp_empty' => '#F0DEE3',
                'border' => '#F0DEE3',
                'radius' => '20px',
                'button_radius' => '9999px',
                'shadow' => '0 6px 18px -8px rgba(192,132,151,0.3)',
            ],
            'art-deco-gold' => [
                'name' => 'Art Deco Gold',
                'blurb' => 'Black and gold — elegant geometric type, upscale evening venue.',
                'google_fonts' => 'Cinzel:wght@600;700|Inter:wght@400;500',
                'heading_font' => "'Cinzel', serif",
                'body_font' => "'Inter', sans-serif",
                'page_bg' => '#0D0D0D',
                'card_bg' => '#1A1A1A',
                'text' => '#F5E6C8',
                'muted' => '#A08A5A',
                'accent' => '#D4AF37',
                'accent_text' => '#0D0D0D',
                'stamp_filled' => '#D4AF37',
                'stamp_empty' => '#2A2A2A',
                'border' => '#3A3A3A',
                'radius' => '2px',
                'button_radius' => '2px',
                'shadow' => '0 8px 24px -8px rgba(212,175,55,0.25)',
            ],
            'farmers-market-rustic' => [
                'name' => 'Farmers Market Rustic',
                'blurb' => 'Kraft paper and mustard — hand-drawn heading, rustic market-stall feel.',
                'google_fonts' => 'Caveat:wght@600;700|Karla:wght@400;500;600',
                'heading_font' => "'Caveat', cursive",
                'body_font' => "'Karla', sans-serif",
                'page_bg' => '#F1E4CC',
                'card_bg' => '#FBF6EC',
                'text' => '#4A3826',
                'muted' => '#9C8362',
                'accent' => '#B5651D',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#B5651D',
                'stamp_empty' => '#E4D2AE',
                'border' => '#E4D2AE',
                'radius' => '10px',
                'button_radius' => '8px',
                'shadow' => '0 6px 16px -6px rgba(74,56,38,0.2)',
            ],
            'arctic-ice-cream' => [
                'name' => 'Arctic Ice Cream',
                'blurb' => 'Icy blue and bubblegum pink — playful and bright, ice-cream-parlour feel.',
                'google_fonts' => 'Baloo+2:wght@600;700|Nunito+Sans:wght@400;600',
                'heading_font' => "'Baloo 2', sans-serif",
                'body_font' => "'Nunito Sans', sans-serif",
                'page_bg' => '#EAF7FB',
                'card_bg' => '#FFFFFF',
                'text' => '#1E4E5F',
                'muted' => '#7FAAB8',
                'accent' => '#FF8FAE',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#FF8FAE',
                'stamp_empty' => '#D7EFF7',
                'border' => '#D7EFF7',
                'radius' => '24px',
                'button_radius' => '9999px',
                'shadow' => '0 8px 20px -8px rgba(255,143,174,0.3)',
            ],
            'urban-skate-barber' => [
                'name' => 'Urban Skate Barber',
                'blurb' => 'Near-black with graffiti neon yellow-green — streetwear barbershop.',
                'google_fonts' => 'Anton|Inter:wght@400;500',
                'heading_font' => "'Anton', sans-serif",
                'body_font' => "'Inter', sans-serif",
                'page_bg' => '#1A1A1A',
                'card_bg' => '#262626',
                'text' => '#F2F2F2',
                'muted' => '#9A9A9A',
                'accent' => '#D4FF3D',
                'accent_text' => '#101000',
                'stamp_filled' => '#D4FF3D',
                'stamp_empty' => '#333333',
                'border' => '#3A3A3A',
                'radius' => '4px',
                'button_radius' => '4px',
                'shadow' => '0 0 20px -4px rgba(212,255,61,0.35)',
            ],
            'mediterranean-terracotta' => [
                'name' => 'Mediterranean Terracotta',
                'blurb' => 'Sand and olive green — sun-baked warmth, deli/olive-oil shop feel.',
                'google_fonts' => 'Marcellus|Karla:wght@400;500;600',
                'heading_font' => "'Marcellus', serif",
                'body_font' => "'Karla', sans-serif",
                'page_bg' => '#F3E5D8',
                'card_bg' => '#FFFBF6',
                'text' => '#4A2E1F',
                'muted' => '#A98363',
                'accent' => '#8A9B6E',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#8A9B6E',
                'stamp_empty' => '#EAD9C4',
                'border' => '#EAD9C4',
                'radius' => '14px',
                'button_radius' => '9999px',
                'shadow' => '0 6px 18px -8px rgba(74,46,31,0.2)',
            ],
            'japanese-minimalist' => [
                'name' => 'Japanese Minimalist',
                'blurb' => 'Off-white and hinomaru red — extremely clean, zen-cafe restraint.',
                'google_fonts' => 'Shippori+Mincho:wght@600;700|Noto+Sans:wght@400;500',
                'heading_font' => "'Shippori Mincho', serif",
                'body_font' => "'Noto Sans', sans-serif",
                'page_bg' => '#FAFAFA',
                'card_bg' => '#FFFFFF',
                'text' => '#1A1A1A',
                'muted' => '#8C8C8C',
                'accent' => '#BC002D',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#BC002D',
                'stamp_empty' => '#EAEAEA',
                'border' => '#EAEAEA',
                'radius' => '2px',
                'button_radius' => '2px',
                'shadow' => '0 1px 3px 0 rgba(0,0,0,0.06)',
            ],
            'autumn-harvest' => [
                'name' => 'Autumn Harvest',
                'blurb' => 'Warm cream and pumpkin orange — cozy seasonal bakery feel.',
                'google_fonts' => 'Yeseva+One|Nunito+Sans:wght@400;600',
                'heading_font' => "'Yeseva One', serif",
                'body_font' => "'Nunito Sans', sans-serif",
                'page_bg' => '#F5E6D3',
                'card_bg' => '#FFFAF0',
                'text' => '#5A2E1A',
                'muted' => '#A67C52',
                'accent' => '#C1440E',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#C1440E',
                'stamp_empty' => '#EAD2B0',
                'border' => '#EAD2B0',
                'radius' => '16px',
                'button_radius' => '9999px',
                'shadow' => '0 8px 20px -8px rgba(193,68,14,0.3)',
            ],
            'punk-pub-grunge' => [
                'name' => 'Punk Pub Grunge',
                'blurb' => 'Near-black with distressed red — stencil type, dive-bar attitude.',
                'google_fonts' => 'Staatliches|Inter:wght@400;500',
                'heading_font' => "'Staatliches', sans-serif",
                'body_font' => "'Inter', sans-serif",
                'page_bg' => '#141414',
                'card_bg' => '#1F1F1F',
                'text' => '#F2F2F2',
                'muted' => '#999999',
                'accent' => '#E63946',
                'accent_text' => '#FFFFFF',
                'stamp_filled' => '#E63946',
                'stamp_empty' => '#2E2E2E',
                'border' => '#333333',
                'radius' => '2px',
                'button_radius' => '2px',
                'shadow' => '0 8px 20px -8px rgba(230,57,70,0.35)',
            ],
        ];
    }

    public function index(): View
    {
        return view('dev.themes.index', ['themes' => self::themes()]);
    }

    public function show(string $slug): View
    {
        abort_unless(array_key_exists($slug, self::themes()), 404);

        return view('dev.themes.show', [
            'slug' => $slug,
            'theme' => self::themes()[$slug],
        ]);
    }
}
